name: Run Kaggle Cinematch Trainer

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  run-kaggle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Kaggle API
        run: |
          pip install kaggle

      - name: Authenticate and Push to Kaggle
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir -p ~/.kaggle
          cat << 'EOF' > ~/.kaggle/kaggle.json
          {
            "username": "${{ secrets.KAGGLE_USERNAME }}",
            "key": "${{ secrets.KAGGLE_KEY }}"
          }
          EOF
          chmod 600 ~/.kaggle/kaggle.json

          export HF_TOKEN=$HF_TOKEN
          kaggle kernels push -p .

      - name: Update Cron Schedule
        uses: gr2m/set-cron-schedule-action@v2
        with:
          token: ${{ secrets.PAT_WITH_WORKFLOW_SCOPE }}
          cron: |
            0 5 * * *
          workflow: run_kaggle.yml
          message: "ci(kaggle): làm mới lịch chạy cron để tránh bị disable"
